import Head from 'next/head'
import { Inter } from '@next/font/google'
import Navbar from "../components/navbar";
import Title from "../components/title";
import Details from "../components/details";
import Footer from "../components/footer";
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Sacred Hearth College</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed&display=swap" rel="stylesheet">
      </Head>

      <Navbar />
      <Title />
      <Details />
      <Footer />
    </>
  )
}
